### ISSUE TITLE
Check all glyphs for drawing errors

### ISSUE THREAD

**Issue by davelab6** [enathu/aaram#4]
I spotted this error :(

<img width="236" alt="screen shot 2016-05-31 at 15 13 53" src="https://cloud.githubusercontent.com/assets/261579/15690756/4f6c1b82-2742-11e6-9033-2f7c88fd89be.png">

**Comment by davelab6** [comment]
(also on last letter of first line)

**Comment by enathu** [comment]
Fixed. :)
