### ISSUE TITLE
Copyright fixes

### ISSUE THREAD

**Issue by vv-monsalve** [enathu/aaram#5]
Taken from the Font Bakery report performed on the font file in the `gh-pages` branch at commit `c195f1a`

These are the reported Fails on copyright strings:

<details>
<summary>🔥 <b>FAIL:</b> Check license file has good copyright string.</summary>

* [com.google.fonts/check/license/OFL_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/license/OFL_copyright)
<pre>--- Rationale ---

An OFL.txt file&#x27;s first line should be the font copyright e.g:
&quot;Copyright 2019 The Montserrat Project Authors
(https://github.com/julietaula/montserrat)&quot;

</pre>

* 🔥 **FAIL** First line in license file does not match expected format: "copyright (c) 2014, tharique azeez (http://niram.org|zeezat@gmail.com)"

</details>
<details>
<summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in fonts</summary>

* [com.google.fonts/check/font_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/font_copyright)

* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: "Copyright 2019 The Familyname Project Authors (git url)"
But instead we have got:
"Copyright (c) 2014 by Tharique Azeez. All rights reserved." [code: bad-notice-format]
* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: "Copyright 2019 The Familyname Project Authors (git url)"
But instead we have got:
"Copyright (c) 2014 by Tharique Azeez. All rights reserved." [code: bad-notice-format]

</details>

**Comment by enathu** [comment]
Fixed. :)
