### ISSUE TITLE
Hinting fixes + Build script

### ISSUE THREAD

**Issue by vv-monsalve** [enathu/aaram#7]
Taken from the Font Bakery report performed on the font file in the `gh-pages` branch at commit `c195f1a`

The following is the reported fail refers to hinting fixes. To solve it, the font could be hinted using ttfautohint or you could use the gftools fix-nonhinting tool. These options could be included in the build script that is part of the [requirements](https://github.com/googlefonts/gf-docs/tree/master/Spec#scalable-font-production) to ensure a repeatable process done in a single step.

This could be a good [example](https://github.com/SorkinType/Varta/blob/master/Sources/build.sh) of the build script.

<details>
<summary>🔥 <b>FAIL:</b> Font enables smart dropout control in "prep" table instructions?</summary>

* [com.google.fonts/check/smart_dropout](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/smart_dropout)
<pre>--- Rationale ---

This setup is meant to ensure consistent rendering quality for fonts across all
devices (with different rendering/hinting capabilities).

Below is the snippet of instructions we expect to see in the fonts:
B8 01 FF    PUSHW 0x01FF
85          SCANCTRL (unconditinally turn on
                      dropout control mode)
B0 04       PUSHB 0x04
8D          SCANTYPE (enable smart dropout control)

&quot;Smart dropout control&quot; means activating rules 1, 2 and 5:
Rule 1: If a pixel&#x27;s center falls within the glyph outline,
        that pixel is turned on.
Rule 2: If a contour falls exactly on a pixel&#x27;s center,
        that pixel is turned on.
Rule 5: If a scan line between two adjacent pixel centers
        (either vertical or horizontal) is intersected
        by both an on-Transition contour and an off-Transition
        contour and neither of the pixels was already turned on
        by rules 1 and 2, turn on the pixel which is closer to
        the midpoint between the on-Transition contour and
        off-Transition contour. This is &quot;Smart&quot; dropout control.

For more detailed info (such as other rules not enabled in this snippet),
please refer to the TrueType Instruction Set documentation.

</pre>

* 🔥 **FAIL** The 'prep' table does not contain TrueType instructions enabling smart dropout control. To fix, export the font with autohinting enabled, or run ttfautohint on the font, or run the `gftools fix-nonhinting` script. [code: lacks-smart-dropout]

</details>

**Comment by enathu** [comment]
Fixed. :)

**Comment by vv-monsalve** [comment]
> included in the build script that is part of the requirements to ensure a repeatable process done in a single step.

The build script file to generate the fonts in a single step is a requirement [as per the Spec](https://github.com/googlefonts/gf-docs/tree/master/Spec#scalable-font-production). Please include it into the `source` folder of the repository.
