### ISSUE TITLE
fsSelection adjustments

### ISSUE THREAD

**Issue by vv-monsalve** [enathu/aaram#9]
Taken from the Font Bakery report performed on the font file in the `gh-pages` branch at commit `c195f1a`

The [fsSelection](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#fsselection) bit 6 –font is Regular, and bit 7 –Use Typo Metrics, must be enabled in the font.
This last one is particularly relevant regarding [Vertical Metrics.](https://github.com/enathu/aaram/issues/8)

<details>
<summary>🔥 <b>FAIL:</b> Checking OS/2 fsSelection value.</summary>

* [com.google.fonts/check/fsselection](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/fsselection)

* 🔥 **FAIL** OS/2 fsSelection REGULAR bit should be set. [code: bad-REGULAR]

</details>

**Comment by enathu** [comment]
Fixed. :)
